# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d30d071b2ccb1014b9874473b3bb1c542321eb43d8b41911d21bb7b609b85340c7fd2ada35cce02af8efe4f96eb60afa80d687084ee942a2d4c201962cd6d2a

test:
  secret_key_base: 0e0999993227c69eccf9996b2918b1e4e626f398f54cfc8f9b223640051049074d89e12f1d3ebb562b8546864a85e4985a2ae3cfcc76da2390ef8d6e28b17049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
